---
title: "Peer-graded Assignment: Getting and Cleaning Data Course Project"
author: "Soma Chowdhury"
date: "2024-04-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Peer-graded Assignment: Getting and Cleaning Data Course Project

This submission by _Soma Chowdhury_ is for the peer graded assignment for Getting and Cleaning Data Course project

## DataSet
Human activity data collected from the accelerometers from the Samsung Galaxy S smartphone  (https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip)

## Files

* Codebook.Rmd
A code book that describes the variables, the data and any transformations or work performed to clean up the data

* run_analysis.R 
R script file that executes steps for 
  * Data preparation
  * Merges the training and test sets to create one data set
  * Extracts only the measurements on the mean and standard deviation for each measurement.
  * Uses descriptive activity names to name the activities in the data set
  * Appropriately labels the data set with descriptive variable names.
  * From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

* FinaData.txt 
Exported final data text file.

